//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Section { get; set; }
        public string Branch { get; set; }
        public string EmailID { get; set; }
    }
}
