USE [REPASOLUNESr]
GO

/****** Object:  StoredProcedure [dbo].[sp_crear_cliente]    Script Date: 22/07/2021 19:29:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE  [dbo].[sp_crear_cliente]
@IDCLIENTE AS VARCHAR(5),
@APELLIDOS AS VARCHAR(30),
@NOMBRES As	 VARCHAR(30)
AS INSERT INTO CLIENTE VALUES(@IDCLIENTE,@APELLIDOS,@NOMBRES);
GO


