<?xml version="1.0" encoding="utf-8"?><Database Name="Hospital1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ASATA403\SQLEXPRESSJUANMA;Initial Catalog=Hospital1;Persist Security Info=True;User ID=sa" SettingsObjectName="Dia_3_del_8_CON_LINQ.Properties.Settings" SettingsPropertyName="Hospital1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Enfermo1" Member="Enfermo1">
    <Type Name="Enfermo1">
      <Column Name="inscripcion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="S" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>