#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANCOREPASOLUNES
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="REPASOLUNESr")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::BANCOREPASOLUNES.Properties.Settings.Default.REPASOLUNESrConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_crear_cliente")]
		public int sp_crear_cliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, aPELLIDOS, nOMBRES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ELIMINARCLIENTE")]
		public int sp_ELIMINARCLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MODIFICAR_CLIENTE")]
		public int SP_MODIFICAR_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, aPELLIDOS, nOMBRES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MOSTRAR_TODA_INFORMACION")]
		public ISingleResult<SP_MOSTRAR_TODA_INFORMACIONResult> SP_MOSTRAR_TODA_INFORMACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((ISingleResult<SP_MOSTRAR_TODA_INFORMACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mostrartodo")]
		public ISingleResult<sp_mostrartodoResult> sp_mostrartodo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_mostrartodoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spbuscarporapellido")]
		public ISingleResult<spbuscarporapellidoResult> spbuscarporapellido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aPELLIDOS);
			return ((ISingleResult<spbuscarporapellidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spbuscarporIDCLIENTE")]
		public ISingleResult<spbuscarporIDCLIENTEResult> spbuscarporIDCLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((ISingleResult<spbuscarporIDCLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spbuscarpornombre")]
		public ISingleResult<spbuscarpornombreResult> spbuscarpornombre([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRES);
			return ((ISingleResult<spbuscarpornombreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_contarcliente")]
		public ISingleResult<sp_contarclienteResult> sp_contarcliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((ISingleResult<sp_contarclienteResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_MOSTRAR_TODA_INFORMACIONResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public SP_MOSTRAR_TODA_INFORMACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class sp_mostrartodoResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public sp_mostrartodoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class spbuscarporapellidoResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public spbuscarporapellidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class spbuscarporIDCLIENTEResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public spbuscarporIDCLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class spbuscarpornombreResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public spbuscarpornombreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class sp_contarclienteResult
	{
		
		private System.Nullable<int> _Column1;
		
		public sp_contarclienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
