CREATE PROCEDURE SP_MODIFICAR_CLIENTE
@IDCLIENTE AS VARCHAR(5),
@APELLIDOS AS  VARCHAR(30),
@NOMBRES AS VARCHAR(30)
AS 
UPDATE   CLIENTE SET  

APELLIDOS=@APELLIDOS,
NOMBRES=@NOMBRES
WHERE IDCLIENTE=@IDCLIENTE;

GO
EXEC SP_MODIFICAR_CLIENTE 'BA001','GUTIERREZ VALLINA','JOSE';